workspace(name = "envoy_example_wasm_cc")

load("//bazel:archives.bzl", "load_envoy_example_wasm_cc_archives")
load_envoy_example_wasm_cc_archives()

load("//bazel:deps.bzl", "resolve_envoy_example_wasm_cc_dependencies")
resolve_envoy_example_wasm_cc_dependencies()

load("//bazel:toolchains.bzl", "load_envoy_example_wasm_cc_toolchains")
load_envoy_example_wasm_cc_toolchains()

load("//bazel:packages.bzl", "load_envoy_example_wasm_cc_packages")
load_envoy_example_wasm_cc_packages()

load("//bazel:toolchains_extra.bzl", "load_envoy_example_wasm_cc_toolchains_extra")
load_envoy_example_wasm_cc_toolchains_extra()
